name: release

on:
  push:
    branches: [ master ]
jobs:
    
  pypi-publish:
    if: contains(github.event.head_commit.message, 'publish')
    environment: release
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3

      - name: Publish package distributions to PyPI
        run: pdm publish